### ISSUE TITLE
template node returns null if there are only dynamic values

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/issues#106]
Template node returns null if there are only dynamic and no static values.

**Comment by benjithedalilama** [comment]
Did some investigating, and this is actually only occuring if there is more than one dynamic value, and there is not a static character in front of the first dynamic value. So if the template contains: 
"{{msg.payload}}dfg{{msg.payload}}", then it will return null. however if it is: "g{{msg.payload}}dfg{{msg.payload}}", it works.
