### ISSUE TITLE
Flow constantly autosaves while page is idle

### ISSUE THREAD

**Issue by chrismatthieu** [octoblu/issues#114]
You can import my twitter sentiment flow from our marketplace and watch it continuously auto-save.  It's rather annoying...

**Comment by benjithedalilama** [comment]
Are there notifications popping up everytime it auto-saves?

**Comment by chrisfleck** [comment]
the browser frame also moves / jumps as it is autosaving

**Comment by sqrtofsaturn** [comment]
Does this issue still occur?

**Comment by chrisfleck** [comment]
seems OK now

**Comment by sqrtofsaturn** [comment]
Closed #114.
