### ISSUE TITLE
Mutated Payload in Debug Node

### ISSUE THREAD

**Issue by chrismatthieu** [octoblu/issues#118]
https://app.octoblu.com/design/import/b82c85cc-9ac1-430d-be45-02fdaf458244

{
  "node": "3eb98950-1a0a-11e5-b022-411b8dc27130",
  "name": "Debug",
  "msgType": "input",
  "msg": {
    "price": 31.01,
    "devices": [
      "370b01b5-1927-44a1-a30b-2147430a4fae"
    ],
    "payload": {
      "on": true,
      "color": "green"
    }
  }
}

**Comment by benjithedalilama** [comment]
I was limiting the scope of flow to be flow in a directive. Closed #118

**Comment by benjithedalilama** [comment]
I was wrong.

**Comment by chrismatthieu** [comment]
Can't duplicate.  Closing...
