### ISSUE TITLE
flow inspector or designer pane needs its own scroll bar

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#123]
Though not always the most intuitive the flow inspector needs its own scroll bar.
For example; I want to add a trigger to my flow.  I scroll down, select the trigger and it adds.
I then have to scroll back to the top to move it to where I need it, except whoops, I totally scrolled past it and lost it.
The first time I think it didn't add, so I go add it again.
Then as I scroll to the top I notice it fly by.  Now I have to move it up near the top.

An alternate method might be to not add it to the center of the designer.
Or, give the designer its own scroll bar.  So it is always in a known location and not scrolling with the page.

**Comment by benjithedalilama** [comment]
Could you clarify a little bit more as to what your suggestion is? I am not sure I understand the features which you are suggesting.

**Comment by brianehlert** [comment]
I think this is now a mute point as the Nodes list now has its own scroll bar, so I don't have to scroll the page to shop through the list of available nodes.

**Comment by benjithedalilama** [comment]
Alright, Closed #123.
