### ISSUE TITLE
When selecting my configured nodes, I am brought to a blank page

### ISSUE THREAD

**Issue by benjithedalilama** [octoblu/issues#124]
![screen shot 2015-06-26 at 7 45 35 pm](https://cloud.githubusercontent.com/assets/10225652/8390183/014f9e0e-1c3c-11e5-80f6-3e5a7bc6a83f.png)

The error I am getting in my console is:

TypeError: Cannot read property 'category' of undefined
    at add-node-wizard-controller.js:8
    at processQueue (angular.js:12988)
    at angular.js:13004
    at Scope.$eval (angular.js:14204)
    at Scope.$digest (angular.js:14020)
    at Scope.$apply (angular.js:14308)
    at done (angular.js:9532)

This is probably because we do not handle $state.go properly for these configured nodes.
We only account for if it is a channel or a device in the add-node-wizard controller. We have to set the state to display the device manager page or the channel manager page.

It looks like nodeType is undefined at that point.

**Comment by oayandosu** [comment]
@benjithedalilama Any more info to help with this issue? I can't replicate it. Do you have any nodes configured? Browser?

**Comment by AlisamfP** [comment]
fixed it!
