### ISSUE TITLE
Manage Channel view does not look great

### ISSUE THREAD

**Issue by benjithedalilama** [octoblu/issues#127]
![screen shot 2015-06-26 at 8 02 22 pm](https://cloud.githubusercontent.com/assets/10225652/8390225/5760ddba-1c3e-11e5-9443-9732100bd8d2.png)

**Comment by sqrtofsaturn** [comment]
It looks like this is an artifact and shouldn't be happening.

**Comment by sqrtofsaturn** [comment]
Fixed anyways until we change how we are doing this. Closed #127
