### ISSUE TITLE
Loading icon in node inspector is broken

### ISSUE THREAD

**Issue by benjithedalilama** [octoblu/issues#132]
![screen shot 2015-06-30 at 10 22 28 am](https://cloud.githubusercontent.com/assets/10225652/8437138/f1f88cda-1f11-11e5-8786-09c7cb5b6864.png)

**Comment by royvandewater** [comment]
What's broken about it?

**Comment by benjithedalilama** [comment]
We had the loading icon centered previously, sorry about the vague issue.

**Comment by royvandewater** [comment]
Cool, makes sense :-)

**Comment by benjithedalilama** [comment]
Closed #132.
