### ISSUE TITLE
node names run over each other

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#134]
There needs to be some way to wrap / split / display differently the names of nodes devices as the names easily run into each other and make discovery very difficult.

**Comment by brianehlert** [comment]
![noderun](https://cloud.githubusercontent.com/assets/2301754/8443301/5356cec4-1f3a-11e5-8d5c-da077e36917d.PNG)

**Comment by brianehlert** [comment]
I would hate for icons to be larger to accommodate a longer single line of text, as they are already pretty big.

**Comment by AlisamfP** [comment]
pushed up a fix for this. Will close when I confirm it's fixed in production.
