### ISSUE TITLE
Using the Login with Citrix always brings you to the "Authorize page"

### ISSUE THREAD

**Issue by johnmcbride** [octoblu/issues#138]
When using the "Login with Citrix" you always get prompted with the authorize page. This should probably only happen once ,the first time a user uses the citrix option.

![image](https://cloud.githubusercontent.com/assets/125551/8527221/91ad09b0-23d9-11e5-898c-af6d1310c1fd.png)

**Comment by kmariano** [comment]
This is not due to Octoblu itself, but it is due to the Citrix Authentication Service saving session tokens in the browser and will bypass the login process and take you to the authorize page. They can probably shorten the lifespan of the session tokens to force the user to log back in.
