### ISSUE TITLE
When activating a channel, save configuration view is shown before the Node's proper auth view loads 

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/issues#140]
Page flashes this view before loading in correct html for the specific auth

<img width="812" alt="screen shot 2015-07-06 at 11 24 27 am" src="https://cloud.githubusercontent.com/assets/10360697/8529768/ba7145bc-23d1-11e5-9157-64c76953dc7f.png">

Properly loaded in:
<img width="999" alt="screen shot 2015-07-06 at 11 27 10 am" src="https://cloud.githubusercontent.com/assets/10360697/8529797/f83ac8f0-23d1-11e5-9b40-4c9256f84b6c.png">

**Comment by benjithedalilama** [comment]
Fixed so it has a loading spinner instead of always showing the default configuration view. Closed #140
