### ISSUE TITLE
In Collection Browser, list items are improperly styled

### ISSUE THREAD

**Issue by benjithedalilama** [octoblu/issues#147]
When clicking on a list in the collection browser, the inner div animation on-click is broken
<img width="1680" alt="screen shot 2015-07-09 at 11 30 20 am" src="https://cloud.githubusercontent.com/assets/10225652/8603566/ec0d2dda-262d-11e5-8224-7c10719d3a1c.png">

The whole entire list item should animate, not just the inner div.

**Comment by sqrtofsaturn** [comment]
they are just regular buttons now, not md, so the ripple effect was lost
