### ISSUE TITLE
Multiple compose nodes share configuration values

### ISSUE THREAD

**Issue by erikwilson** [octoblu/issues#152]

**Comment by erikwilson** [comment]
When using the flow designer and compose nodes, when switching between compose nodes the values remain the same (except for name). 
See: https://app.octoblu.com/design/import/bf52d810-e27d-4a89-9ff0-fc67f94dd570

Clicking between Compose A, Compose B, and Compose C yields false values. Clicking on non-compose node as intermediate steps produces correct values.

**Comment by benjithedalilama** [comment]
Is this still an issue?
