### ISSUE TITLE
Designer should center on opening of flows

### ISSUE THREAD

**Issue by virgilvox** [octoblu/issues#156]

**Comment by benjithedalilama** [comment]
Why exactly would we do this? People come back to a flow in the view they were working on. Why would we want to move the view?

**Comment by erikwilson** [comment]
I agree that the designer should center on flows now that flow centering has been fixed. The designer is currently ignoring zoomScaleX and zoomScaleY values, they should probably be removed from the model along with zoomScale value. Perhaps there should be a max viewBox size enforced, with a toast warning on center if the flow is larger than that max size.

**Comment by oayandosu** [comment]
I like that idea. I'm not a fan of the toast warning though. I think the user will figure that out without the warning. We've had a few users request this feature today. +1

**Comment by benjithedalilama** [comment]
Understood, considering the new center button, my heart has changed

**Comment by benjithedalilama** [comment]
Looks like this fix is live, Closed #156
