### ISSUE TITLE
Sidebar toggle buttons ( - / + ) for flow inspector & things are broken

### ISSUE THREAD

**Issue by erikwilson** [octoblu/issues#157]

**Comment by benjithedalilama** [comment]
What about them is broken?

**Comment by erikwilson** [comment]
After collapsing there is no way to expand the collapsed category.
After clicking ( - ) on Flow Inspector the ( - ) on Things becomes a ( + ).
After closing both Flow Inspector and Things the filter bar does nothing.

**Comment by chrismatthieu** [comment]
The filter search box and grid icon should also disappear when the things section is collapsed.

**Comment by oayandosu** [comment]
Fixed
