### ISSUE TITLE
Things lack help

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#174]
In the Things view of the Octoblu UI, Things have a name and when I click on them they have setup detail.
However, thy lack any description of what they actually do, an example of why I would want to use them, or other guidance to help me decide if this node is a useful thing and how I might use it.
I see descriptions in the designer, but not in the Things view when I select a thing to see what it does.

I generally don't use the designer to discover nodes and what they might do.  If I am in the designer I have already decided what it is that I want to do and generally have an idea what I want to do it with.
When exploring what I want to do, I generally begin in the Things tab.
The same goes for exploring operations and channels.
The Designer UI does not lend itself to exploration that well.

**Comment by sqrtofsaturn** [comment]
We added a description to the page you see when adding a thing from the Things section. There is also required dependencies for anything added to Gateblu.
