### ISSUE TITLE
All Things Are Offline

### ISSUE THREAD

**Issue by arianais** [octoblu/issues#186]
Please help me fix my Gateblu!

{
  "server": "meshblu.octoblu.com",
  "port": 443,
  "uuid": "c4bd24e0-b587-11e4-81c7-dd5049b34083",
  "token": "ee806e7492a64ab43f8fd1e6e1eb0ad5697576f9",
  "nodePath": "",
  "devicePath": "/Users/ariana/Library/Application Support/GatebluService/devices",
  "tmpPath": "/Users/ariana/Library/Application Support/GatebluService/tmp"
}

**Comment by erikwilson** [comment]
Possibly related to tmp/node_modules which need to be updated, error similar to

Wed, 29 Jul 2015 21:25:22 GMT gateblu-forever:connector-manager updateConnector meshblu-wemo /Users/xxx/Library/Application Support/GatebluService/tmp
Wed, 29 Jul 2015 21:25:23 GMT gateblu:command uncaughtException [TypeError: object is not a function]
null
null

from /var/log/gateblu-error.log.

Need better update procedure to ensure any dependencies are also updated.
Need to use NPM cache separate from user NPM cache.
Need better feedback of where in the setup process installation currently is.
