### ISSUE TITLE
Editing device properties on things page is unusable

### ISSUE THREAD

**Issue by iamruinous** [octoblu/issues#192]
Attached is a video of me trying to type in a simple url. Looks like the debounce is broken.

https://www.dropbox.com/s/oepgyby1b5yr6wk/octoblu-edit-thing.mp4?dl=0

**Comment by kmariano** [comment]
I would like us to go away from auto-saving properties on the device details page and other pages and have a save button so the user can initiate the update. It simplifies things and we have the added benefit of avoiding having to rely on debounce to wait for user input.

**Comment by oayandosu** [comment]
Agreed. I'm working on it.
