### ISSUE TITLE
The Claim Things function is broken

### ISSUE THREAD

**Issue by kmariano** [octoblu/issues#193]
When you try to claim a thing with a valid uuid and token and the device is open, you cannot claim it on the Claim Things page . 

https://app.octoblu.com/node-wizard/claim

<img width="1439" alt="screen shot 2015-08-11 at 9 25 23 am" src="https://cloud.githubusercontent.com/assets/565178/9203260/ea42b230-400a-11e5-99c6-07ff3659e04d.png">

**Comment by sqrtofsaturn** [comment]
It looks like you put the UUID in the token input and vice versa. We cannot reproduce the issue.
