### ISSUE TITLE
Active Flows are no longer indicated in the designer drop down

### ISSUE THREAD

**Issue by kmariano** [octoblu/issues#194]
If a flow is running or active, the state is no longer indicated in the drop down
<img width="1440" alt="screen shot 2015-08-11 at 10 04 30 am" src="https://cloud.githubusercontent.com/assets/565178/9204185/7bac6a36-4010-11e5-95b7-7c54bfd0546d.png">

**Comment by sqrtofsaturn** [comment]
Fixed in master, not production yet

**Comment by AlisamfP** [comment]
Fixed in production
