### ISSUE TITLE
Adding Blink1 to Gateblu results in MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#198]
I am still stuck with non-functioning blink1 on Gateblu on Windows10 x64
I just reinstalled the Gateblu Service, claimed it, added the Blink1
The only log I can find is %localappdata%\Octoblu\GatebluService\device<guid>\forever.stderr

Which only says:
{ [Error: Cannot find module 'node-blink1'] code: 'MODULE_NOT_FOUND' }

I see that the module downloaded. It is at path:
C:\Users\Brian\AppData\Local\Octoblu\GatebluService\tmp\node_modules\meshblu-blink1

I am at a loss. But it made for a real poor demo experience yesterday.

Currently testing with Windows8.1 and Linux.  Making this issue as a placeholder while I have to reboot.

**Comment by brianehlert** [comment]
I have the same result on Windows 8.1 x64
So, It is not a Windows 10 specific issue.

**Comment by brianehlert** [comment]
Still getting this error today on Raspian Jessie.
I am guessing that the Blink(1) Node is dead (?)

**Comment by brianehlert** [comment]
> meshblu@1.30.1 preinstall /home/pi/gateblu-service/tmp/node_modules/meshblu-blink1/node_modules/meshblu
> node -e "try{require('./skip-install.js')}catch(e){}"

No precompiled binary found
npm WARN deprecated node-hid@0.4.1: bad semver, NANv2 change means we shoudl be v0.5.0, NANv1 is 0.4.0
npm WARN installMany request was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree

**Comment by brianehlert** [comment]
I finally have a workaround for this.

Prior to pushing the plug-in by adding the node:
sudo apt-get install -y libusb-1.0-0-dev libudev-dev
sudo npm install -g -y node-hid --unsafe-perm 

The plug-in installs node-hid - which actually tosses some small error though it looks like it installs.  Using the --unsafe-perm option gets past that, and actually lets the plug-in push and install succeed.

Then after updating the firewall rules, the Blink(1) needs to be removed and reinserted.

**Comment by virgilvox** [comment]
Added to the docs for Blink1 https://meshblu-connectors.readme.io/v1.0/docs/blink1
