### ISSUE TITLE
Something strange happening with tokens and multiple windows

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#20]
I frequently use multiple browsers and browser windows to have multiple flows open at the same time for reference and demo.
What I have noticed on my windows machine is that I frequently get into issues where I will see incorrect things between the windows.
I have attempted to use 'InPrivate' in IE and 'private window' in Firefox to allow this, and I am starting to think that it actually makes things worse.
Today I had a flow open in Firefox, I went to the template screen and copied a URL.  Then I opened an InPrivate IE session and logged on as a different user.
I pasted the URL.  Once I clicked the cloud to import the flow, my Firefox browser started flashing and flipping between screens and eventually logged itself out.
Very, very strange.

My expectation is that I can login as two users on the same workstation using InPrivate / Incognito / Private to isolate the session from each other.  And this does not seem to be the case.

I have had other strange issues as well.  When I logon as one user, then as a another user, where on some screens I am the correct user for the window and on other screens I see that I am the 'wrong' user but the permissions reflect as if I am the 'correct' user.  
It is almost as if the token is at the machine level and not the browser session level.  And that this can impact cross browsers is also interesting.

**Comment by brianehlert** [comment]
Just had another account crossover.
I am logged in as user A, I create a template, I copy the link.  I then use the Sign Out button.
I then logon as user B.  I paste the template import URL, I am then taken to the designer and I see the list of flows for user A (not user B) which I have no permissions to, so I notice that none of them are running (that is my initial clue that things are messed up).

**Comment by royvandewater** [comment]
I think the Firefox -> IE issue may have been a coincidence. There was a failed deploy yesterday that caused the exact infinite redirect symptoms you described.

I'm trying to reproduce the copying a link, Signout, Login and import issue, but can't seem to make it happen. Did you have multiple Octoblu tabs open? Are there any additional details you could provide?

**Comment by brianehlert** [comment]
I see it quite frequently - since I also frequently have two accounts open at the same time, and the behavior seems worse when I use InPrivate / Private for one and not the other.

And I get behavior that is different if I use one window and sign out between accounts.

The inconsistency is strange. 

When it is not too convenient, I use a laptop to have one window open, and my workstation for the other.

I am starting to wonder if it is a windows specific thing.

From: Roy van de Water
Sent: ‎Wednesday‎, ‎May‎ ‎6‎, ‎2015 ‎3‎:‎03‎ ‎PM
To: octoblu/issues
Cc: Brian Ehlert

I think the Firefox -> IE issue may have been a coincidence. There was a failed deploy yesterday that caused the exact infinite redirect symptoms you described.

I'm trying to reproduce the copying a link, Signout, Login and import issue, but can't seem to make it happen. Did you have multiple Octoblu tabs open? Are there any additional details you could provide?

**Comment by royvandewater** [comment]
I've tried to reproduce this in Windows IE, but have been unable to do so. It should not be possible for us to pollute sessions across inPrivate/regular IE, or across browsers, even if we wanted to. 

Closing this until we have a way to reproduce the issue.
