### ISSUE TITLE
Sending message to Blink1 is refused "Error: connect ECONNREFUSED]"

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#202]
I have been trying in vain to get Blink1 working on Gateblu with Windows and Linux for days now.

On Linux I have had to add libusb-1.0-0.dev in order to get HID.node.

After that I send a message to my configured Blink1 and in the stdout I have the following:
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

I tried this using docker as well and mapping the USB bus into the docker instance and received the same error.

I am at a loss.  I cannot use the Blink on Windows nor Linux at this time.

**Comment by brianehlert** [comment]
I am also seeing:
[Error: Cannot find module './build/Release/HID.node'] code: 'MODULE_NOT_FOUND' 
in the stderr output

**Comment by brianehlert** [comment]
I just upgraded to the latest version of gateblu and there is no change.  But there is additional information.

Forever.stderr:
{ [Error: Cannot find module './build/Release/HID.node'] code: 'MODULE_NOT_FOUND' }

Forever.stdout:
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

GatebluService.log:
2015-08-21 11:26:31,402 [5] ERROR GatebluServiceTray.Program - tar and request not available, skipping precompiled binary fetch
2015-08-21 11:26:33,402 [5] ERROR GatebluServiceTray.Program - npm WARN installMany request was bundled with meshblu-blink1@3.3.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:33,433 [5] ERROR GatebluServiceTray.Program - npm WARN installMany tar was bundled with meshblu-blink1@3.3.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:33,444 [5] ERROR GatebluServiceTray.Program - npm WARN installMany fstream was bundled with meshblu-blink1@3.3.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:35,357 [7] ERROR GatebluServiceTray.Program - npm WARN installMany request was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:35,362 [5] ERROR GatebluServiceTray.Program - npm WARN installMany tar was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:35,390 [5] ERROR GatebluServiceTray.Program - npm WARN installMany fstream was bundled with meshblu@1.30.1, but bundled package wasn't found in unpacked tree
2015-08-21 11:26:42,266 [5] ERROR GatebluServiceTray.Program - gypnpm WARN optional dep failed, continuing node-blink1@0.1.6
2015-08-21 11:26:46,703 [7] ERROR GatebluServiceTray.Program - gypgypnpm WARN optional dep failed, continuing utf-8-validate@1.1.0
2015-08-21 11:26:46,707 [7] ERROR GatebluServiceTray.Program - npm WARN optional dep failed, continuing bufferutil@1.1.0

**Comment by brianehlert** [comment]
First - fix node-hid by doing a global install with unsafe-perms prior to adding the node to the Gateblu:

sudo apt-get install -y libusb-1.0-0-dev libudev-dev
sudo npm install -g -y node-hid --unsafe-perm 

After this, the meshblu-blink1 and its dependency on node-blink1 will actually install properly.
And, after updating the udev permissions the Blink(1) needs to be unplugged and plugged back in.

this was from Gateblu on the RaspberryPi

**Comment by sqrtofsaturn** [comment]
Just to clarify, are you using the documentation at https://gateblu.octoblu.com/docs/raspberry-pi for installation on a Debian system?

The following udev rules:
`sudo curl -o /etc/udev/rules.d/51-blink1.rules https://raw.githubusercontent.com/todbot/blink1/master/linux/51-blink1.rules  && \
sudo udevadm control --reload-rules`

 should allow access without the need for unsafe-perms or global install

**Comment by brianehlert** [comment]
The udev rules are fine, **but if the Blink(1) was plugged in, you still need to remove it and plug it back in.**
(that idea came from the Blink1 github site)

I did the global install on node-hid as a way to understand what was going wrong with node-hid and get past an EACCESS as root error.
I ended up opening a bug with node-hid and learned that there is a gcc dependency that when met will probably remove the other errors.

The error was not related to libusb I was installaing:
sudo apt-get install -y libusb-1.0-0-dev libudev-dev

I also had to install gateblu-forever with unsafe-perms to get past errors there.

And I had to tell npm to use python 2.7 (since the latest Raspberry pi includes python 2 and 3.
npm config set python /usr/bin/python2.7

In the end, I had the plug-ins I was testing installing without any errors, and the Blink(1) was working - whish I have not had working for a very long time due to plug-in installation errors.

Still working out my details I will post as soon and my additional tweaks to https://gateblu.octoblu.com/docs/raspberry-pi are fully working.

**Comment by sqrtofsaturn** [comment]
Please keep in mind that gateblu should be run as a normal user rather than root for security purposes.

Thanks for offering to contribute to the documentation!

**Comment by brianehlert** [comment]
Here are my manual steps which results in the (troublesome) modules (tested) properly installing when pushed from Octoblu:

Node and Node ARM have been updated.  
Node 4 requires updated gcc binaries.

To set Raspian to boot without a GUI desktop (and get a bit more performance):
sudo raspi-config
Boot options
B1 or B2 console option
reboot

1) Update gcc (required for node 4)
sudo apt-get update
sudo apt-get install -y gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

2) Install node for ARM
echo "deb http://node-arm.herokuapp.com/ /" | sudo tee --append /etc/apt/sources.list
sudo apt-get update
sudo apt-get install node -y --force-yes
node -v

3) Update npm
sudo npm -g update npm

4) set git to use https instead: of git: (for port blocking of git port 9418)
sudo git config --global url.https://.insteadOf git://

5) Global install of node-gyp for modules
sudo npm install -g -y node-gyp

6) Node-gyp requires python 2.7 (only) and Raspian Jessie has multiple version of python installed.  
If calling node-gyp directly use the environment variable declaration: node-gyp --python /usr/bin/python2.7
npm config set python /usr/bin/python2.7

7) To support direct attached USB devices with Gateblu (such as Blink(1))
sudo apt-get install -y libusb-1.0-0-dev libudev-dev
sudo npm install -g -y node-hid --unsafe-perm 

There is still an install error reported when installing node-hid this way, but node-hid reports as being installed.  Not installing it this way but as part of meshblu-blink1 node-hid is reported as not being installed.

8) Install Gateblu Service
sudo npm install -g gateblu-forever --unsafe-perm
sudo curl -o /etc/init.d/gateblu-service https://raw.githubusercontent.com/octoblu/gateblu-forever/master/.installer/raspbian/init.d/gateblu-service 
sudo chmod +x /etc/init.d/gateblu-service
sudo update-rc.d gateblu-service defaults

9) Start Gateblu
sudo service gateblu-service start

10) Find the UUID and token
Wait a minute or two after starting Gateblu.  We need it to generate an identity and write the meshblu.json file.  
cd gateblu-service
Do an ls a couple times until the meshblu.json configuration file is written.
Nano meshblu.json
*you will need to copy and paste the uuid and token

11) Claim the Gateblu instance
Open Things,  Scroll down to Octoblu, Select Gateblu, select Connect Gateblu, select Already Downloaded, select Claim an Existing Thing, add a name and paste the uuid and token,  select Connect Gateblu

Blink1:  Due to udev permissions issues, you need to follow this step to allow the pi user to have write access to the blink1.
sudo curl -o /etc/udev/rules.d/51-blink1.rules https://raw.githubusercontent.com/todbot/blink1/master/linux/51-blink1.rules
sudo udevadm control --reload-rules
Unplug and re-plug the Blink(1) - if you don't it will not work.

**Comment by virgilvox** [comment]
That is a very good guide there, @brianehlert it would be cool if you did a blog post or a write-up version of it. If you like maybe there is a place for it in the docs somewhere. I'm thinking of adding a user made guides section on octoblu-designer.readme.io
