### ISSUE TITLE
On add-node page, toolbar scrolls with page view, iti should be stationary

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/issues#203]
<img width="1214" alt="screen shot 2015-08-14 at 12 44 52 pm" src="https://cloud.githubusercontent.com/assets/10360697/9282592/543d796c-4282-11e5-9369-5c590b2ef682.png">

**Comment by sqrtofsaturn** [comment]
fixed, not in production

**Comment by AlisamfP** [comment]
fixed in production
