### ISSUE TITLE
Windows uninstall reports that it cannot stop the running service

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#204]
GatebluServiceTray.exe - the icon is removed from the Windows Tray as if the service has stopped, however the process is still present (if you look at task manager) but has stopped consuming resources.

If all components of the GatebluService are stopped prior to uninstall the uninstaller falsely reports that it cannot stop the applications and forces a reboot on me unnecessarily.

**Comment by AlisamfP** [comment]
This should be fixed in version 5.0.5 of the Gateblu Service and version 3.4.5 of the UI
