### ISSUE TITLE
I can no longer rename tempaltes / give templates unique names

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#21]
Since templates are the only safety net / out of band saving mechanism I would rename them to make points in time unique.

Such as naming a template to correspond with a Sprint end.

All I have is the base name of the flow and a time stamp.  And someone could rename the base flow and suddenly I have to look at each and every flow to identify the one with the changes I need to see / pull out / get the correct version that I need to revert to.

**Comment by AlisamfP** [comment]
We are currently making some changes to the templates page to make this more obvious, but you are able to update the name of a template by changing the name on the templates page.
