### ISSUE TITLE
unconfigured generic node setup link from designer doesn't work

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/issues#219]
When importing a flow with an unconfigured generic device node, the setup link from the designer goes to https://app.octoblu.com/node-wizard/add/ instead of https://app.octoblu.com/node-wizard/add/53c9b832f400e177dca325b3

(the icon is also a little bit larger for the unconfigured node)

Was able to recreate this with this bluprint 
https://app.octoblu.com/bluprints/import/2a898a00-4002-4fb6-a039-d524e5a3783a

**Comment by AlisamfP** [comment]
fixed!
