### ISSUE TITLE
I frequently only want to drag a node around the desiger screen - properties annoyance

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#22]
To put it in the right place for a wire to look correct and I don't want the properties of the node to pop out all of the time as I am now trying to place the node under the properties popup.

I don't have tiny 1024 x 768 monitors, but I don't have unlimited real estate either.
And the properties popping out is getting to be more of a nuisance than an aid in my getting work done.

**Comment by royvandewater** [comment]
This is also a huge problem on mobile/tablets. We are currently working on a fix and should have it out within the next few days.

**Comment by iamruinous** [comment]
new sidebar is live!
