### ISSUE TITLE
String equality filter

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#227]
I would love a string equality filter that does a === against a string.

I have all kinds of function nodes that have ifs in them only to match the string value of a particular key.
Such as: ((body.action) === "enter")

It would be super swell if it also had an ignore case option.

**Comment by brianehlert** [comment]
Triple bonkers if I can do multiple strings.
ie.  (((body.device) === "Participant A") && ((body.action === "exit")))

**Comment by iamruinous** [comment]
How does this differ from the equal node? (for string equality that is)

**Comment by brianehlert** [comment]
All of the filters except NULL have the statement;
"Supported inputs include: date and numbers"

**Comment by redaphid** [comment]
Ah. That was supposed to mean in _addition_ to strings. At one point, they only supported strings! So your request should work just fine as-is.

**Comment by brianehlert** [comment]
I am trying it, and strings are not making it through.
So either it really does not support strings, or I am way off in how I am using it.

The msg exiting the trigger is:

{
  "node": "0afa16a0-7998-11e5-a92e-cb6df15435e1",
  "name": "Debug",
  "msgType": "input",
  "msg": {
    "from": "d010f8c0-745a-11e5-9aa8-372bca6ff2e1",
    "params": {
      "email": "Two@foo.com",
      "firstname": "Two",
      "device": "Participant B",
      "action": "enter"
    }
  }
}

The equality filter is set as:  {{msg.params.device}} = "Participant B"

it does not match, nothing makes it.

**Comment by brianehlert** [comment]
Instruction / documentation bug then.

Strings seem to work.  At least for the Equality.
Not sure how to handle strings if it is not NULL or Equal.

The equality filter handling more than one value would be valuable, I could reduce the number of filter nodes in the flow.
I can only assume that would have a net positive impact on the system.

**Comment by miql** [comment]
Equality filter docs/help text updated.
