### ISSUE TITLE
When I first add a node to the designer I want to name it

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#23]
When  first add a node I would like to give it a unique name, then I want to edit other properties.
the Function node ( for example) takes me straight to the editor.

If I select a node that is already added to the flow, I might not want to edit the name, in that came I would most likely default to some other property / setting.  And here is the function node behavior of going straight to the editor is most likely what I would like to do.

**Comment by AlisamfP** [comment]
The name field (the top most field in each node's editor), allows you to change the names of your nodes to unique ones.

These names also apply when searching using the designer's search bar (for example, if you change your function node's name to cats, it will only show up by searching for "cats", not "function").

**Comment by brianehlert** [comment]
You missed the point of my issue.  This is not about finding nodes. This is about the cursor focus tied to actions / stages in the process of building a flow.
Your comments do not address what I was referring to.

**Comment by royvandewater** [comment]
I think @AlisamfP may have been talking about this input box:

![screenshot 2015-05-06 10 08 18](https://cloud.githubusercontent.com/assets/72016/7498734/07657c0a-f3d8-11e4-94f8-11846ab1441a.png)

That name field only affects that particular instance of the node. Does this meet your needs?

**Comment by royvandewater** [comment]
@redaphid pointed out how you were talking about cursor focus when first shown the form. I think that it'll be hard for us to predict what the user would like to edit first, so having the first field in all forms focused by default would probably be the most predictable behavior

**Comment by royvandewater** [comment]
One of the most convenient ways to delete nodes is by selecting them and pressing the backspace key. Focusing on the first input field would disable that, forcing the user to do more work to delete the node. I'm going to close this for now.
