### ISSUE TITLE
Unable to bluprint flows

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#234]
The attached flows will not bluprint
[LiveDemov4.json.txt](https://github.com/octoblu/issues/files/33587/LiveDemov4.json.txt)

**Comment by brianehlert** [comment]
The one pattern that I have now noticed.
If I copy and paste nodes in the Designer, then I am not able to bluprint.

**Comment by brianehlert** [comment]
[CalendarSample.json.txt](https://github.com/octoblu/issues/files/36957/CalendarSample.json.txt)

**Comment by brianehlert** [comment]
I created a new flow.  Then updated it with the Nodes, Links, Name, and Description from this JSON source.
I have the same result of not being able to bluprint.

**Comment by brianehlert** [comment]
This has to be tied to the number of or content of Compose Nodes that I have.
I exported the JSON and then imported into a new flow and the compose nodes went all strange and broke all of the strings within a compose node into sub arrays.

**Comment by brianehlert** [comment]
Pretty sure that the root of the issue is me declaring array positions in compose nodes for keys.
key = payload.Lync[0].Command

(Jade told me I could and showed me how)  ;-)

**Comment by iamruinous** [comment]
I think we got this fixed. There was a problem using dynamic keys in the compose node. You may need to hard-refresh to make sure you get the latest version of the compose.html page.

**Comment by brianehlert** [comment]
My flows still don't bluprint.
Went as far as closing browser to reset.
Has the change been pushed?

**Comment by iamruinous** [comment]
Be sure to click on your compose node and make sure everything looks ok

**Comment by brianehlert** [comment]
I just clicked on my compose nodes in one of the flows that did not bluprint and (thankfully) I don't care about.
When I select the Compose nodes, nothing displays.  They appear blank (with no key value pairs)

**Comment by iamruinous** [comment]
you may have to clear your cache. The HTML page changed but the browser doesn't seem to notice it.

**Comment by brianehlert** [comment]
I fear clicking on the compose nodes in my critical flows.
The simple one that no longer displays has 1 trigger.  and 4 compose nodes. and three delays, and one target device
Each compose node has two or three key value pairs.

Such as:
CloseApp = payload.Lync[0].Command
DoItNow = payload.Lync[0].Argiment

**Comment by brianehlert** [comment]
I have to dump my cache entirely?
Closing an re-opening is not picking up the change?  (this is firefox)

**Comment by iamruinous** [comment]
I had to clear my cache to make it work. I couldn't get Chrome to recognize the new page, even though `no-cache` is turned on for that page.

Or try a different browser.

**Comment by brianehlert** [comment]
Okay, that did it for FireFox too.  After I forced it to clear the broswer cache, it displayed the Compose correctly and allowed me to BluPrint one of the flows.

The most complex of the flows still does not bluprint.

If the issue is sitll Compose node related it has one with {{ }} combined with the dynamic keys.
One with a dynamic key that is three nested keys in the array, plus a key that is not dynamic.

An another a bit more complex:
CloseApp = payload.Lync[0].Command
DoItNow = payload.Lync[0].Argiment
CloseApp = payload.Lync[1].Command
DoItNow = payload.Lync[1].Argiment
CloseApp = payload.Foo[0].Command
DoItNow = payload.Foo[0].Argiment

**Comment by brianehlert** [comment]
The key to this ended up being a change in the Compose Node.
The 'older' version of the Compose Node that were in my flows would not blueprint (or save after the above fix was implemented).
The workaround required that I open each compose node in the designer so that they would update and then the flow would both blueprint or save.

The issue that I would like to see derived from this is that there either needs to be a better way to update nodes, or there needs to be a less manual process, possibly a flow level process when I investigate a flow that is not functioning instead of node by node.
In the end, the requirement should be less stumbling and manual intervention required by the customer.
