### ISSUE TITLE
http://app.octoblu.com open sourced?

### ISSUE THREAD

**Issue by ajagnanan** [octoblu/issues#245]
Hello, is the designer open sourced too?

**Comment by chrismatthieu** [comment]
Approximately 80% of our IoT stack is open source.  The designer and the computing engine are not.

**Comment by ajagnanan** [comment]
Are there any plans to open source those too?

**Comment by chrismatthieu** [comment]
Not at this time...

**Comment by ajagnanan** [comment]
Ok, thank you
