### ISSUE TITLE
app.octoblu.com does not open in Edge

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#251]
I just rebuilt my workstation with Windows10 (fdisk, format, install).
I opened Edge and entered the URL  app.octoblu.com
And Edge just sits there and does nothing.
FireFox works.  So there is something specific that the Designer is doing that Edge does not like.

The impact; alienating an entire browser and the potential users.

**Comment by erikwilson** [comment]
Is working on my Windows 10 Install:

![screenshot 1](https://cloud.githubusercontent.com/assets/1999874/13088186/7b794bec-d4a8-11e5-9380-0b8a9a9a8c44.png)

Is your OS up to date? Are you able to provide any debugging information?

**Comment by brianehlert** [comment]
![image](https://cloud.githubusercontent.com/assets/2301754/13090989/e0a30544-d4ad-11e5-83b6-8711abd98f57.png)

Here is what I have.
I think the key here is that this is a brand new Windows install.

**Comment by brianehlert** [comment]
![403](https://cloud.githubusercontent.com/assets/2301754/13091094/530a36c0-d4ae-11e5-811c-5ca81cdd87b0.PNG)

**Comment by erikwilson** [comment]
Those errors aren't actually problems, bootstrap is complaining about some less files not loading but they aren't required. If you scroll down there might be some actually useful errors.

Can you please make sure that your OS has all updates installed and try again?

**Comment by brianehlert** [comment]
I updated and rebooted a couple times and now it seems okay.
Very strange.
Sorry for the bug.
