### ISSUE TITLE
Interval Node stops pulsing

### ISSUE THREAD

**Issue by royvandewater** [octoblu/issues#3]
I have had multiple flows that stop pulsing / triggering when left alone. 

In some cases it appears to actually be running but not visible. In others the flow has stopped and needs to be restarted.

**Comment by chrisfleck** [comment]
This happens with Chrome. 
here is a flow that stops . It was after a about 10 min.. but now seems like if i leave it overnight 
https://app.octoblu.com/design/import/20000010-ee9b-11e4-83e5-1129589e64aa

**Comment by royvandewater** [comment]
Updated meshblu npm so that it'll try to resubscribe on reconnect. Should fix this
