### ISSUE TITLE
When a node becomes deactivated, it is unremovable in a flow.

### ISSUE THREAD

**Issue by benjithedalilama** [octoblu/issues#30]
If you deactivate a node and it exists in flows, you are unable to remove it from that flow. In order to remove the node you must setup the node.

**Comment by royvandewater** [comment]
This looks like its going to be rather difficult to fix. An immediate work around is to search for the node in the omnibox, select it that way, then pressing delete

**Comment by royvandewater** [comment]
Whoops

**Comment by sqrtofsaturn** [comment]
Fixed!
