### ISSUE TITLE
When I add a new device if I wait, I end up claiming

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#36]
For example, I am adding a new device - an arduino.
I select add new.
I click the name box.
If I type too slow, the UUID gets filled in and I end up claiming some device that is online.

**Comment by royvandewater** [comment]
This whole process needs to be thunk out a bit better. Perhaps if we have users state what they want to do first (Create New OR Claim from List OR Claim by UUID & Token), then showing them UI that's more tailored to their choice.

**Comment by iamruinous** [comment]
Similar to the gateblu download / already downloaded buttons.

**Comment by miql** [comment]
Changed UI so that you can now select the action (Add an Unclaimed Device, Claim an Existing Device, Register New Device)
![screen shot 2015-05-21 at 5 21 23 pm](https://cloud.githubusercontent.com/assets/53533/7761692/dc8aae58-ffdd-11e4-9f7a-8d94ae0b256a.png)

**Comment by miql** [comment]
Fixed
