### ISSUE TITLE
When using send message in a Chromecast device, it can't send {{msg.payload}}, only text

### ISSUE THREAD

**Issue by ASteinheiser** [octoblu/issues#37]
When you tell it to display {{msg.payload}}, it will literally display {{msg.payload}}

**Comment by royvandewater** [comment]
I think our Meshblu Device forms don't support the template syntax yet. I'll see if I can add it. Immediate work around is to craft the message using a function node before the Chromecast device and enabling "Forward Message" on the Chromecast node.

**Comment by royvandewater** [comment]
Meshblu Device Nodes now support christacheio (mustache) syntax
