### ISSUE TITLE
pages snap to top on button press

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/issues#5]
Might be caused by having forms inside forms (formception)

**Comment by royvandewater** [comment]
Seems to happen on add-node wizard, specifically:
- on add gateblue after picking a subdevice, when clicking the button on the bottom

**Comment by royvandewater** [comment]
Looks like it may be caused by #25

**Comment by royvandewater** [comment]
Can no longer reproduce since #25 has been deployed. Please reopen with steps to reproduce if it happens again
