### ISSUE TITLE
Cannot Delete Flows

### ISSUE THREAD

**Issue by royvandewater** [octoblu/issues#60]
![screen shot 2015-05-21 at 1 10 25 pm](https://cloud.githubusercontent.com/assets/72016/7757938/d69a86b2-ffba-11e4-9d35-8c61fa033b3d.png)

![screen shot 2015-05-21 at 1 10 10 pm](https://cloud.githubusercontent.com/assets/72016/7757939/d6ab231e-ffba-11e4-88de-9144d6384949.png)

**Comment by sqrtofsaturn** [comment]
fixed.
