### ISSUE TITLE
Make "null" recognizable in operator = node 

### ISSUE THREAD

**Issue by chrisfleck** [octoblu/issues#64]
It would be helpful to use the = operator node recognize null to help workflows. 
if i set {{msg.foo}} = null . This could be used in many ways to make sure data is coming through or not.  ( is there a simple alternative ? )

**Comment by benjithedalilama** [comment]
You could initially set {{msg.foo}} as -1 and later check if the value changed or if it is still -1, to see if it is modified.

**Comment by chrismatthieu** [comment]
I believe that @erikwilson added a new null operator filter yesterday...

**Comment by erikwilson** [comment]
We have added a new Null Filter (with an optional not toggle), please see the following bluprint as an example of checking a message for a not null value:
https://app.octoblu.com/design/import/1188e405-038a-4ef7-bc57-73ed36e4908c

**Comment by chrisfleck** [comment]
Works , thanks !
