### ISSUE TITLE
Octoblu display is impacted by size of IE window

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#74]
If an IE browser window is too small, many Octoblu screens do not render. (such as Design, Process, Analyze, Profile).
The IE window appears blank in these cases.  dragging the window wider will suddenly cause it to render.
And if you place Firefox and IE side by side, it appears that Octoblu is simply broken for the IE browser.
And for all cases (if my monitor is not big enough) it is.
![ie_1](https://cloud.githubusercontent.com/assets/2301754/7989985/9a510cc4-0aa2-11e5-816a-9c670e0b1c14.PNG)
![ie_2](https://cloud.githubusercontent.com/assets/2301754/7989987/9a540172-0aa2-11e5-8fd8-ec82144a2e68.PNG)
![ieunusable_1](https://cloud.githubusercontent.com/assets/2301754/7989990/9a549a60-0aa2-11e5-8073-41730365da1d.PNG)
![ieunusable_2](https://cloud.githubusercontent.com/assets/2301754/7989986/9a521e70-0aa2-11e5-8d44-d9c4e19d4be8.PNG)
![ieunusable_3](https://cloud.githubusercontent.com/assets/2301754/7989989/9a5424e0-0aa2-11e5-9dbc-ed44a7fce1a2.PNG)
![ieunusable_4](https://cloud.githubusercontent.com/assets/2301754/7989988/9a541658-0aa2-11e5-90c0-2ca3fc1d6db3.PNG)
![ieunusable_5](https://cloud.githubusercontent.com/assets/2301754/7989991/9a62c978-0aa2-11e5-8272-6a9d6e7d01ec.PNG)
![ieunusable_6](https://cloud.githubusercontent.com/assets/2301754/7989992/9a663392-0aa2-11e5-9a8e-218a69318310.PNG)

**Comment by oayandosu** [comment]
Issue fixed!
