### ISSUE TITLE
Error returns when trying to use the reset token button under profile

### ISSUE THREAD

**Issue by johnmcbride** [octoblu/issues#87]
When trying to use the Reset Token button located under the profile options in the OctoBlu site it returns "Error resetting token".

See attached screen shot
![resettoken_error](https://cloud.githubusercontent.com/assets/125551/8044345/fcc71632-0df9-11e5-82e9-58088cc64bf9.png)

**Comment by royvandewater** [comment]
This has been swapped for 'Generate Token', a much less destructive (and more functional) feature :-)
