### ISSUE TITLE
There should be an API to get individual flows

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#95]
I can do a number of things with flows through the API.
The one thing that I cannot do is GET an individual flow.  I can only get all flows that I own.
For modifying flows through the API, it would be excellent if I could GET an individual flow, modify it, and then PUT it with the modifications.
The current workflow really only supports creating new flows. (empty shell, populate the shell, put the flow, start the flow, stop the flow)

**Comment by iamruinous** [comment]
Added
