### ISSUE TITLE
Chat help icon missing 

### ISSUE THREAD

**Issue by chrisfleck** [octoblu/issues#99]
Was helping someone with a flow and noticed the chat help button missing per the pic. He had Win 8.1 with Chrome. ( on my mac & xendesktop the icon shows up fine ) 

![bug](https://cloud.githubusercontent.com/assets/12160685/8185706/e1604b78-1413-11e5-8779-327c42d4d856.JPG)

**Comment by ASteinheiser** [comment]
Hey Chris,
So just I tried to replicate this problem on my Win 8.1 laptop, however, the chat icon popped up for me. Maybe we could GoToMeeting with whoever was having this problem to see if it's something in his environment?

**Comment by chrisfleck** [comment]
- vishal

**Comment by oayandosu** [comment]
Seems to work fine, I can't replicate the issue across multiple browsers. I'm going to close the issue for now.
